from __future__ import annotations

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .model import PredictionResult


def build_prediction_report(
    output_path: str | Path,
    source_filename: str,
    result: PredictionResult,
) -> Path:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    styles = getSampleStyleSheet()
    document = SimpleDocTemplate(str(output), pagesize=A4)
    story = [
        Paragraph("EEG Seizure Detection Report", styles["Title"]),
        Spacer(1, 16),
        Paragraph(f"Source file: {source_filename}", styles["Normal"]),
        Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]),
        Spacer(1, 16),
    ]

    data = [
        ["Prediction", result.label_name.upper()],
        ["Confidence", f"{result.confidence:.2%}"],
        ["Decision threshold", f"{result.threshold:.2f}"],
        ["Positive class", "ictal/seizure"],
    ]
    table = Table(data, colWidths=[160, 260])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef2f7")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#111827")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.extend([table, Spacer(1, 16)])
    story.append(
        Paragraph(
            "This report is generated by a research prototype and is not a medical diagnosis.",
            styles["Italic"],
        )
    )
    document.build(story)
    return output
